import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Image, StyleSheet, Text, View } from 'react-native';
import { colors, radii } from '../theme';
import { AppContent, Player } from '../types';

export function StatsScreen({ content, wide }: { content: AppContent; wide: boolean }) {
  const goals = content.players.reduce((sum, item) => sum + item.goals, 0);
  const appearances = content.players.reduce((sum, item) => sum + item.appearances, 0);
  const leaders = [...content.players].sort((a, b) => b.goals - a.goals || b.appearances - a.appearances).slice(0, 5);
  return <View style={styles.stack}><Header /><View style={[styles.metrics, wide && styles.metricsWide]}><Metric icon="account-group-outline" value={content.players.length} label="Calciatori" /><Metric icon="soccer" value={goals} label="Gol rosa" /><Metric icon="run" value={appearances} label="Presenze" /></View><View style={[styles.columns, wide && styles.columnsWide]}><View style={styles.card}><Text style={styles.eyebrow}>PRIMA SQUADRA</Text><Text style={styles.cardTitle}>Marcatori</Text>{leaders.map((player, index) => <Leader key={player.id} player={player} rank={index + 1} />)}</View><View style={styles.card}><Text style={styles.eyebrow}>SERIE D</Text><Text style={styles.cardTitle}>Classifica</Text>{content.standings.slice(0, 8).map((row) => <View key={`${row.rank}-${row.club}`} style={styles.standing}><Text style={styles.rank}>{row.rank}</Text><Text style={styles.club}>{row.club}</Text><Text style={styles.played}>{row.played}</Text><Text style={styles.points}>{row.points}</Text></View>)}</View></View></View>;
}
function Header() { return <View><Text style={styles.eyebrow}>NUMERI</Text><Text style={styles.title}>Statistiche</Text><Text style={styles.copy}>Rendimento della rosa, marcatori e classifica del campionato.</Text></View>; }
function Metric({ icon, value, label }: { icon: React.ComponentProps<typeof MaterialCommunityIcons>['name']; value: number; label: string }) { return <View style={styles.metric}><View style={styles.metricIcon}><MaterialCommunityIcons name={icon} size={24} color={colors.accentStrong} /></View><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function Leader({ player, rank }: { player: Player; rank: number }) { return <View style={styles.leader}><Text style={styles.rank}>{rank}</Text><View style={styles.avatar}>{player.imageUrl ? <Image source={{ uri: player.imageUrl }} resizeMode="cover" style={styles.avatarImage} /> : null}</View><View style={styles.leaderBody}><Text style={styles.leaderName}>{player.name}</Text><Text style={styles.leaderMeta}>{player.role} · {player.appearances} presenze</Text></View><Text style={styles.goal}>{player.goals}</Text></View>; }
const styles = StyleSheet.create({ stack: { gap: 18 }, eyebrow: { color: colors.yellow, fontSize: 11, fontWeight: '900' }, title: { color: colors.ink, fontSize: 37, fontWeight: '900', marginTop: 4 }, copy: { color: colors.muted, fontSize: 15, lineHeight: 22, fontWeight: '700', marginTop: 8 }, metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, metricsWide: { flexWrap: 'nowrap' }, metric: { flexGrow: 1, minWidth: 105, padding: 16, borderRadius: radii.lg, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line }, metricIcon: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surfaceRaised }, metricValue: { color: colors.ink, fontSize: 25, fontWeight: '900', marginTop: 12 }, metricLabel: { color: colors.muted, fontSize: 11, fontWeight: '700' }, columns: { gap: 14 }, columnsWide: { flexDirection: 'row' }, card: { flex: 1, padding: 18, borderRadius: radii.lg, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line }, cardTitle: { color: colors.ink, fontSize: 24, fontWeight: '900', marginTop: 3, marginBottom: 12 }, leader: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.lineSoft }, rank: { width: 28, color: colors.accentStrong, fontWeight: '900' }, avatar: { width: 44, height: 44, borderRadius: 22, overflow: 'hidden', backgroundColor: colors.surfaceSoft }, avatarImage: { width: '100%', height: '100%' }, leaderBody: { flex: 1 }, leaderName: { color: colors.ink, fontWeight: '900' }, leaderMeta: { color: colors.muted, fontSize: 10, marginTop: 2 }, goal: { color: colors.accentStrong, fontSize: 18, fontWeight: '900' }, standing: { flexDirection: 'row', alignItems: 'center', minHeight: 45, borderBottomWidth: 1, borderBottomColor: colors.lineSoft }, club: { flex: 1, color: colors.ink, fontWeight: '800' }, played: { width: 32, textAlign: 'center', color: colors.muted }, points: { width: 36, textAlign: 'center', color: colors.ink, fontWeight: '900' } });
