import { MaterialCommunityIcons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import { useState } from 'react';
import { Alert, Image, Pressable, Switch, Text, View } from 'react-native';
import { colors } from '../../theme';
import { AppContent, NewsArticle } from '../../types';
import { Button, Field, adminStyles } from './Primitives';

const id = () => `news-${Date.now()}`;
export function NewsAdmin({ content, onChange }: { content: AppContent; onChange: (next: AppContent) => Promise<void> }) {
  const [title, setTitle] = useState(''); const [category, setCategory] = useState('Società'); const [summary, setSummary] = useState(''); const [body, setBody] = useState(''); const [imageUrl, setImageUrl] = useState(''); const [sourceUrl, setSourceUrl] = useState(''); const [featured, setFeatured] = useState(false);
  const pick = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.Images, allowsEditing: true, aspect: [16, 9], quality: 0.75, base64: true }); if (!result.canceled) { const asset = result.assets[0]; setImageUrl(asset.base64 ? `data:${asset.mimeType ?? 'image/jpeg'};base64,${asset.base64}` : asset.uri); } };
  const add = () => { if (!title.trim() || !summary.trim() || !imageUrl.trim()) return Alert.alert('Campi mancanti', 'Titolo, riassunto e immagine sono obbligatori.'); const article: NewsArticle = { id: id(), title: title.trim(), category: category.trim() || 'News', summary: summary.trim(), body: body.trim() || summary.trim(), imageUrl, sourceUrl: sourceUrl || undefined, source: 'Redazione APPrato', publishedAt: new Intl.DateTimeFormat('it-IT', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date()).toUpperCase(), featured }; const previous = featured ? content.news.map((item) => ({ ...item, featured: false })) : content.news; void onChange({ ...content, news: [article, ...previous] }); setTitle(''); setSummary(''); setBody(''); setImageUrl(''); setSourceUrl(''); setFeatured(false); };
  return <View style={{ gap: 14 }}><View style={adminStyles.panel}><Text style={adminStyles.title}>Crea notizia</Text><Text style={adminStyles.copy}>La copertina fotografica è obbligatoria.</Text><View style={adminStyles.preview}>{imageUrl ? <Image source={{ uri: imageUrl }} resizeMode="cover" style={adminStyles.previewImage} /> : <MaterialCommunityIcons name="image-outline" size={50} color={colors.mutedDark} />}</View><Button label="Carica copertina" icon="image-plus" secondary onPress={() => void pick()} /><Field label="URL immagine" value={imageUrl.startsWith('data:') ? '' : imageUrl} onChangeText={setImageUrl} keyboardType="url" /><View style={adminStyles.row}><Field label="Titolo" value={title} onChangeText={setTitle} /><Field label="Categoria" value={category} onChangeText={setCategory} /></View><Field label="Riassunto" value={summary} onChangeText={setSummary} multiline /><Field label="Testo completo" value={body} onChangeText={setBody} multiline /><Field label="Link fonte" value={sourceUrl} onChangeText={setSourceUrl} keyboardType="url" /><View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 15 }}><Text style={adminStyles.listTitle}>In evidenza</Text><Switch value={featured} onValueChange={setFeatured} trackColor={{ true: colors.accentStrong }} /></View><Button label="Pubblica notizia" icon="send-outline" onPress={add} /></View><View style={adminStyles.panel}><Text style={adminStyles.title}>Notizie pubblicate</Text><View style={adminStyles.list}>{content.news.map((article) => <View key={article.id} style={adminStyles.listRow}><Image source={{ uri: article.imageUrl }} resizeMode="cover" style={{ width: 58, height: 46, borderRadius: 9 }} /><View style={adminStyles.listBody}><Text numberOfLines={2} style={adminStyles.listTitle}>{article.title}</Text><Text style={adminStyles.listMeta}>{article.category} · {article.publishedAt}</Text></View><Pressable onPress={() => void onChange({ ...content, news: content.news.filter((item) => item.id !== article.id) })}><MaterialCommunityIcons name="trash-can-outline" size={20} color={colors.live} /></Pressable></View>)}</View></View></View>;
}
